id = "tflint"
name = "tflint"
description = "Support for TFLint"
version = "0.1.0"
schema_version = 1
authors = ["Michael Grubb <michael@grubb.co>"]
repository = "https://github.com/mgrubb/zed-tflint"

[language_servers.tflint]
name = "tflint"
languages = ["Terraform"]
